### ISSUE TITLE
Test nested facets

### ISSUE THREAD

**Issue by joaogarin** [joaogarin/graphql_search_api#4]

**Comment by duartegarin** [comment]
Solr facets don't have the concept of hierarchy so I don't think this should be in the scope of this module.
The best approach from what I can see is return the terms and parents (basically the hierarchy) together with the search response.

Something like this:
`{
  anabranch_connect_indexSolrSearch(facets: {field: "study_field_tids", min_count: 1, missing: true, limit: 10, operator: "="}) {
    solrDocs {
      title
    }
    solrFacets {
      solrFacetName
      solrFacetValues {
        solrFacetFilter
        solrFacetCount
      }
    }
  }
  taxonomyTermQuery{
    entities{
      ... on TaxonomyTermStudyField{
        name
        parent{
          targetId
        }
      }
    }
  }
}
`

Which will return something like this:
`{
  "data": {
    "anabranch_connect_indexSolrSearch": {
      "solrDocs": [
        {
          "title": "TEST 2 change8"
        },
        {
          "title": "TEST 2 change8"
        },
        {
          "title": "TEST 1"
        },
        {
          "title": "University of Sydney"
        }
      ],
      "solrFacets": [
        {
          "solrFacetName": "study_field_tids",
          "solrFacetValues": [
            {
              "solrFacetFilter": "\"2\"",
              "solrFacetCount": 3
            },
            {
              "solrFacetFilter": "\"1\"",
              "solrFacetCount": 2
            },
            {
              "solrFacetFilter": "\"3\"",
              "solrFacetCount": 2
            },
            {
              "solrFacetFilter": "\"4\"",
              "solrFacetCount": 1
            },
            {
              "solrFacetFilter": "!",
              "solrFacetCount": 1
            }
          ]
        }
      ]
    },
    "taxonomyTermQuery": {
      "entities": [
        {
          "name": "Health",
          "parent": []
        },
        {
          "name": "Engineering",
          "parent": []
        },
        {
          "name": "Education",
          "parent": []
        },
        {
          "name": "Sciences",
          "parent": []
        },
        {},
        {}
      ]
    }
  }
}`

Unfortunately as you can see the parents come up empty.
This is due to the issue raised here: https://www.drupal.org/node/2543726
It has already been fixed in core and should be released in 8.6.

In the frontend you should be able to merge the two responses in order to obtain the "depth" for each term in the taxonomy and then reflect it in the UI.

**Comment by joaogarin** [comment]
Interesting. ok sounds good 👍

**Comment by duartegarin** [comment]
Let's close this one?
