### ISSUE TITLE
Index hardcoded in SolrField Derivative

### ISSUE THREAD

**Issue by duartegarin** [joaogarin/graphql_search_api#5]
The Solr index is hardcoded in the derivative so crashes this module on install, unless you change it to an existing index.

**Comment by joaogarin** [comment]
I quick fixed it. I still want to make this better so that one can only select fields from the right index..but I am finding it hard to make this work. for now it just autosuggests all fields from any index :/ not great. some room for improvement. fixed in https://github.com/joaogarin/graphql_search_api/commit/7dd2f4d719e5dd54fadc4f2bccd713ac3af99175
